services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=identity'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
