version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-identity
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: identity
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./mysql-identity-data:/var/lib/mysql
    networks:
        - identity-network

  redis:
    container_name: redis-identity
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_AOF_ENABLED=yes
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/bitnami/redis/data
    networks:
        - identity-network

#  debezium:
#    image: debezium/connect:latest
#    container_name: debezium
#    ports:
#      - 8083:8083
#    environment:
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: debezium-config
#      OFFSET_STORAGE_TOPIC: debezium-offset
#      STATUS_STORAGE_TOPIC: debezium-status
#      BOOTSTRAP_SERVERS: kafka:9092

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.4.0
#    hostname: zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    healthcheck:
#      test: [ "CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  broker:
#    image: confluentinc/cp-kafka:7.4.0
#    hostname: broker
#    container_name: broker
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    ports:
#      - "9092:9092"
#      - "9101:9101"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_JMX_PORT: 9101
#      KAFKA_JMX_HOSTNAME: localhost
#    healthcheck:
#      test: [ "CMD", "bash", "-c", 'nc -z localhost 9092' ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  mysql-data:
    driver: local

networks:
    identity-network:
        driver: bridge