logging:
  level:
    org.springframework.security: TRACE

spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/identity
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9898

management:
  endpoints:
    web:
      exposure:
        include: '*'
webauthn:
  origin: https://dba34d200f1cb35f.ngrok.app
  rpName: "Bank of Purple"
  rpId: "dba34d200f1cb35f.ngrok.app"
  rpIcon: "https://dba34d200f1cb35f.ngrok.app/favicon.ico"
  displayName: "Bank of Purple"


