#file: noinspection SpringBootApplicationYaml
logging:
  level:
    org.springframework.security: TRACE

spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/identity
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  docker:
    compose:
      lifecycle-management: none

server:
  port: 9898

management:
  endpoints:
    web:
      exposure:
        include: '*'

webauthn:
  origin: "https://fintechmobile.io"
  rpName: "Bank of Purple"
  rpId: "fintechmobile.io"
  rpIcon: "https://d278mjrzpbrzy0.cloudfront.net/favicon.ico"
  displayName: "Bank of Purple"


